NAVER_CLIENT_ID: EhO58HcmVFqTWcJ3zcBW
NAVER_CLIENT_SECRET: VOxrlAMyCP

# KAKAO_CLIENT_ID: 3b3a1623444fb2d417ed4726074114db
# KAKAO_CLIENT_SECRET: JwpFekMB2nZxOXFBiwnizH5NYOi62lPj

KAKAO_CLIENT_ID: 74639fc16680566b9120edfeca7c437b
KAKAO_CLIENT_SECRET: 5cFHklCKW5GKn6w6VgwUnDBJu85ecQIJ
