-- NeighborTrade PostgreSQL/Supabase 2차 테이블 schema and sample DML
-- 작성일: 2026-05-11 월
-- 목적:
-- - 기존 1차 SQL(neighborTrade_db_postgre_supabase_20260511월.sql)에 없는 2차 기능 테이블을 추가한다.
-- - PostGIS 위치 인증 컬럼을 추가한다.
-- - 2차 기능 샘플 데이터를 INSERT한다.
-- - UPDATE, DELETE 예시를 제공한다.
--
-- 실행 위치:
-- - Supabase SQL Editor
--
-- 실행 전 주의:
-- - 이 스크립트는 기존 1차 테이블(neighborhood, member, product_post, trade, review)이 이미 있다고 가정한다.
-- - 기존 데이터를 삭제하지 않는 CREATE IF NOT EXISTS / ALTER IF NOT EXISTS 중심 스크립트이다.
-- - 샘플 INSERT는 1차 샘플 데이터의 id 값(동네 1, seller 2, buyer 3, 판매글 1 등)을 기준으로 한다.
-- - 운영 DB에서는 INSERT/UPDATE/DELETE 예시 구간을 실행하기 전에 데이터를 확인한다.

CREATE EXTENSION IF NOT EXISTS postgis;

-- ==========================================================
-- 0. updated_at trigger function
-- ==========================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==========================================================
-- 1. PostGIS columns for neighborhood
-- ==========================================================

ALTER TABLE neighborhood
    ADD COLUMN IF NOT EXISTS boundary geometry(MultiPolygon, 4326),
    ADD COLUMN IF NOT EXISTS center_point geography(Point, 4326);

UPDATE neighborhood
SET center_point = ST_SetSRID(ST_MakePoint(center_longitude, center_latitude), 4326)::geography
WHERE center_point IS NULL;

CREATE INDEX IF NOT EXISTS idx_neighborhood_boundary
    ON neighborhood USING GIST (boundary);

CREATE INDEX IF NOT EXISTS idx_neighborhood_center_point
    ON neighborhood USING GIST (center_point);

-- boundary 샘플 입력 예시
-- 실제 서비스에서는 행정동 경계 GeoJSON/공공데이터를 변환해서 입력한다.
-- 아래 예시는 가산동 중심 근처의 임시 사각형 MultiPolygon이다.
UPDATE neighborhood
SET boundary = ST_GeomFromText(
    'MULTIPOLYGON(((126.8600 37.4650, 126.9100 37.4650, 126.9100 37.4900, 126.8600 37.4900, 126.8600 37.4650)))',
    4326
)
WHERE id = 1
  AND boundary IS NULL;

-- ==========================================================
-- 2. product_image: 판매글 이미지
-- ==========================================================

CREATE TABLE IF NOT EXISTS product_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_post_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    representative BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_image_post
        FOREIGN KEY (product_post_id) REFERENCES product_post(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_product_image_post
    ON product_image (product_post_id, sort_order);

-- ==========================================================
-- 3. community_post: 동네생활 게시글
-- ==========================================================

CREATE TABLE IF NOT EXISTS community_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    neighborhood_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'VISIBLE',
    view_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_community_post_author
        FOREIGN KEY (author_id) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT fk_community_post_neighborhood
        FOREIGN KEY (neighborhood_id) REFERENCES neighborhood(id),
    CONSTRAINT chk_community_post_status
        CHECK (status IN ('VISIBLE', 'HIDDEN'))
);

CREATE INDEX IF NOT EXISTS idx_community_post_neighborhood_status
    ON community_post (neighborhood_id, status, created_at DESC);

DROP TRIGGER IF EXISTS trg_community_post_updated_at ON community_post;
CREATE TRIGGER trg_community_post_updated_at
BEFORE UPDATE ON community_post
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ==========================================================
-- 4. community_comment: 동네생활 댓글
-- ==========================================================

CREATE TABLE IF NOT EXISTS community_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_post_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_community_comment_post
        FOREIGN KEY (community_post_id) REFERENCES community_post(id) ON DELETE CASCADE,
    CONSTRAINT fk_community_comment_author
        FOREIGN KEY (author_id) REFERENCES member(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_community_comment_post
    ON community_comment (community_post_id, created_at);

-- ==========================================================
-- 5. report: 신고
-- ==========================================================

CREATE TABLE IF NOT EXISTS report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    target_type VARCHAR(40) NOT NULL,
    target_id BIGINT NOT NULL,
    reason VARCHAR(100) NOT NULL,
    detail VARCHAR(1000),
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    processor_note VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    CONSTRAINT fk_report_reporter
        FOREIGN KEY (reporter_id) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT chk_report_target_type
        CHECK (target_type IN ('PRODUCT_POST', 'COMMUNITY_POST', 'COMMUNITY_COMMENT', 'CHAT_MESSAGE')),
    CONSTRAINT chk_report_status
        CHECK (status IN ('RECEIVED', 'REVIEWING', 'RESOLVED', 'REJECTED'))
);

CREATE INDEX IF NOT EXISTS idx_report_status_created
    ON report (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_report_target
    ON report (target_type, target_id);

-- ==========================================================
-- 6. chat_room: 채팅방
-- ==========================================================

CREATE TABLE IF NOT EXISTS chat_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_post_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    buyer_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_room_product_post
        FOREIGN KEY (product_post_id) REFERENCES product_post(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_room_seller
        FOREIGN KEY (seller_id) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_room_buyer
        FOREIGN KEY (buyer_id) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT chk_chat_room_not_self
        CHECK (seller_id <> buyer_id),
    CONSTRAINT uk_chat_room_post_buyer
        UNIQUE (product_post_id, buyer_id)
);

CREATE INDEX IF NOT EXISTS idx_chat_room_seller
    ON chat_room (seller_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_chat_room_buyer
    ON chat_room (buyer_id, updated_at DESC);

DROP TRIGGER IF EXISTS trg_chat_room_updated_at ON chat_room;
CREATE TRIGGER trg_chat_room_updated_at
BEFORE UPDATE ON chat_room
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ==========================================================
-- 7. chat_message: 채팅 메시지
-- ==========================================================

CREATE TABLE IF NOT EXISTS chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_message_room
        FOREIGN KEY (chat_room_id) REFERENCES chat_room(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_message_sender
        FOREIGN KEY (sender_id) REFERENCES member(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_message_room
    ON chat_message (chat_room_id, created_at);

-- ==========================================================
-- 8. manner_score_history: 매너 점수 이력
-- ==========================================================

CREATE TABLE IF NOT EXISTS manner_score_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    review_id BIGINT,
    before_score DOUBLE PRECISION NOT NULL,
    after_score DOUBLE PRECISION NOT NULL,
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_manner_history_member
        FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT fk_manner_history_review
        FOREIGN KEY (review_id) REFERENCES review(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_manner_history_member
    ON manner_score_history (member_id, created_at DESC);

-- ==========================================================
-- 9. INSERT: sample data
-- ==========================================================

-- 판매글 이미지 샘플 (동일 DB에 2차 스크립트를 반복 실행할 때 중복을 피하려면 id 1~10 판매글의 이미지 행을 먼저 삭제합니다.)
DELETE FROM product_image WHERE product_post_id BETWEEN 1 AND 10;

INSERT INTO product_image
    (product_post_id, original_filename, stored_filename, image_url, content_type, file_size, sort_order, representative)
VALUES
    (1, 'desk-main.png', 'pp-01-main.png', 'https://picsum.photos/seed/ntpp1main/640/480', 'image/png', 128400, 0, TRUE),
    (1, 'desk-detail.png', 'pp-01-detail.png', 'https://picsum.photos/seed/ntpp1detail/640/480', 'image/png', 98200, 1, FALSE),
    (2, 'monitor-front.png', 'pp-02-main.png', 'https://picsum.photos/seed/ntpp2main/640/480', 'image/png', 156800, 0, TRUE),
    (2, 'monitor-back.png', 'pp-02-back.png', 'https://picsum.photos/seed/ntpp2back/640/480', 'image/png', 142100, 1, FALSE),
    (3, 'spring-book-cover.png', 'pp-03-main.png', 'https://picsum.photos/seed/ntpp3main/640/480', 'image/png', 89400, 0, TRUE),
    (3, 'spring-book-spine.png', 'pp-03-spine.png', 'https://picsum.photos/seed/ntpp3spine/640/480', 'image/png', 72100, 1, FALSE),
    (4, 'temp-listing.png', 'pp-04-main.png', 'https://picsum.photos/seed/ntpp4main/640/480', 'image/png', 21000, 0, TRUE),
    (5, 'cuckoo-rice-cooker.png', 'pp-05-main.png', 'https://picsum.photos/seed/ntpp5main/640/480', 'image/png', 198300, 0, TRUE),
    (5, 'cuckoo-inner-pot.png', 'pp-05-inner.png', 'https://picsum.photos/seed/ntpp5inner/640/480', 'image/png', 165400, 1, FALSE),
    (6, 'lego-classic-box.png', 'pp-06-main.png', 'https://picsum.photos/seed/ntpp6main/640/480', 'image/png', 112500, 0, TRUE),
    (7, 'nike-shoes-side.png', 'pp-07-main.png', 'https://picsum.photos/seed/ntpp7main/640/480', 'image/png', 134200, 0, TRUE),
    (7, 'nike-shoes-sole.png', 'pp-07-sole.png', 'https://picsum.photos/seed/ntpp7sole/640/480', 'image/png', 108900, 1, FALSE),
    (8, 'yoga-mat-roll.png', 'pp-08-main.png', 'https://picsum.photos/seed/ntpp8main/640/480', 'image/png', 87600, 0, TRUE),
    (9, 'succulent-set.png', 'pp-09-main.png', 'https://picsum.photos/seed/ntpp9main/640/480', 'image/png', 99100, 0, TRUE),
    (9, 'succulent-close.png', 'pp-09-close.png', 'https://picsum.photos/seed/ntpp9close/640/480', 'image/png', 104200, 1, FALSE),
    (10, 'dog-food-bag.png', 'pp-10-main.png', 'https://picsum.photos/seed/ntpp10main/640/480', 'image/png', 123700, 0, TRUE);

UPDATE product_post p
SET representative_image_url = i.image_url
FROM product_image i
WHERE i.product_post_id = p.id
  AND i.representative = TRUE
  AND p.id BETWEEN 1 AND 10;

-- 동네생활 샘플 게시글
INSERT INTO community_post
    (id, author_id, neighborhood_id, title, content, status, view_count)
VALUES
    (1, 2, 1, '가산동 택배 분실 조심하세요', '최근 공동현관 앞 택배 분실 이야기가 있어 서로 조심하면 좋겠습니다.', 'VISIBLE', 12),
    (2, 3, 1, '주말에 같이 산책하실 분 있나요?', '가산디지털단지역 근처에서 가볍게 산책하실 이웃을 찾습니다.', 'VISIBLE', 7),
    (3, 2, 1, '숨김 처리 예시용 동네생활 글', '관리자 숨김 처리 예시를 위한 글입니다.', 'VISIBLE', 1)
ON CONFLICT (id) DO NOTHING;

-- 동네생활 댓글 샘플
INSERT INTO community_comment
    (community_post_id, author_id, content)
VALUES
    (1, 3, '저도 조심해야겠네요. 공유 감사합니다.'),
    (2, 2, '시간 맞으면 같이 걸어도 좋겠습니다.');

-- 채팅방 샘플
INSERT INTO chat_room
    (id, product_post_id, seller_id, buyer_id)
VALUES
    (1, 1, 2, 3)
ON CONFLICT (product_post_id, buyer_id) DO NOTHING;

-- 채팅 메시지 샘플
INSERT INTO chat_message
    (chat_room_id, sender_id, content)
VALUES
    (1, 3, '안녕하세요. 책상 아직 거래 가능할까요?'),
    (1, 2, '네, 아직 가능합니다. 가산디지털단지역 근처에서 거래 가능합니다.');

-- 신고 샘플
INSERT INTO report
    (reporter_id, target_type, target_id, reason, detail, status)
VALUES
    (3, 'PRODUCT_POST', 1, '거래 정보 확인 필요', '상품 설명과 사진이 더 필요해 보입니다.', 'RECEIVED'),
    (2, 'COMMUNITY_POST', 3, '부적절한 테스트 글', '숨김 처리 예시를 위한 신고입니다.', 'REVIEWING');

-- 매너 점수 이력 샘플
INSERT INTO manner_score_history
    (member_id, review_id, before_score, after_score, reason)
VALUES
    (2, 1, 38.5, 39.0, '거래 후기 별점 5점 반영');

-- 수동 id 입력 이후 identity sequence 값을 보정한다.
SELECT setval(pg_get_serial_sequence('product_image', 'id'), COALESCE((SELECT MAX(id) FROM product_image), 1));
SELECT setval(pg_get_serial_sequence('community_post', 'id'), COALESCE((SELECT MAX(id) FROM community_post), 1));
SELECT setval(pg_get_serial_sequence('chat_room', 'id'), COALESCE((SELECT MAX(id) FROM chat_room), 1));

-- ==========================================================
-- 10. UPDATE examples
-- ==========================================================

-- 동네생활 게시글 수정 예시
UPDATE community_post
SET
    title = '가산동 택배 분실 조심하세요 - 내용 추가',
    content = '최근 공동현관 앞 택배 분실 이야기가 있어 서로 조심하면 좋겠습니다. 배송 완료 알림을 받으면 빨리 확인해 주세요.'
WHERE id = 1;

-- 동네생활 글 관리자 숨김 처리 예시
UPDATE community_post
SET status = 'HIDDEN'
WHERE id = 3;

-- 신고 처리 완료 예시
UPDATE report
SET
    status = 'RESOLVED',
    processor_note = '관리자가 내용을 확인하고 숨김 처리했습니다.',
    processed_at = CURRENT_TIMESTAMP
WHERE target_type = 'COMMUNITY_POST'
  AND target_id = 3;

-- 채팅방 updated_at 갱신 예시
UPDATE chat_room
SET updated_at = CURRENT_TIMESTAMP
WHERE id = 1;

-- 매너 점수 변경 이력 추가 예시
INSERT INTO manner_score_history
    (member_id, review_id, before_score, after_score, reason)
VALUES
    (3, NULL, 36.5, 36.8, '2차 기능 테스트용 매너 점수 보정');

-- ==========================================================
-- 11. DELETE examples
-- ==========================================================

-- 테스트용 댓글 삭제 예시
DELETE FROM community_comment
WHERE content = '저도 조심해야겠네요. 공유 감사합니다.';

-- 테스트용 채팅 메시지 삭제 예시
DELETE FROM chat_message
WHERE content = '안녕하세요. 책상 아직 거래 가능할까요?';

-- 반려된 신고 삭제 예시
DELETE FROM report
WHERE status = 'REJECTED'
  AND created_at < CURRENT_TIMESTAMP - INTERVAL '30 days';

-- ==========================================================
-- 12. SELECT: table/schema/data check queries
-- ==========================================================

-- 2차 테이블 생성 확인
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
      'product_image',
      'community_post',
      'community_comment',
      'report',
      'chat_room',
      'chat_message',
      'manner_score_history'
  )
ORDER BY table_name;

-- neighborhood PostGIS 컬럼 확인
SELECT
    column_name,
    data_type,
    udt_name,
    is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'neighborhood'
  AND column_name IN ('boundary', 'center_point')
ORDER BY ordinal_position;

-- 2차 샘플 데이터 건수 확인
SELECT 'product_image' AS table_name, COUNT(*) AS row_count FROM product_image
UNION ALL
SELECT 'community_post', COUNT(*) FROM community_post
UNION ALL
SELECT 'community_comment', COUNT(*) FROM community_comment
UNION ALL
SELECT 'report', COUNT(*) FROM report
UNION ALL
SELECT 'chat_room', COUNT(*) FROM chat_room
UNION ALL
SELECT 'chat_message', COUNT(*) FROM chat_message
UNION ALL
SELECT 'manner_score_history', COUNT(*) FROM manner_score_history;

-- PostGIS 인증 쿼리 예시: 좌표가 가산동 샘플 boundary 안에 있는지 확인
SELECT
    id,
    display_name,
    ST_Contains(boundary, ST_SetSRID(ST_MakePoint(126.87877, 37.478542), 4326)) AS contains_sample_point
FROM neighborhood
WHERE id = 1
  AND boundary IS NOT NULL;
